name = "RadialBasisFunctionModels"
uuid = "48790e7e-73b2-491a-afa5-62818081adcb"
authors = ["Manuel Berkemeier"]
version = "0.1.0-DEV"

[deps]
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticPolynomials = "62e018b1-6e46-5407-a5a7-97d4fbcae734"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ThreadSafeDicts = "4239201d-c60e-5e0a-9702-85d713665ba7"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ChainRules = "^0.7.64, 0.8"
ForwardDiff = "0.10"
Lazy = "0.15"
Memoization = "0.1"
StaticArrays = "1.2"
StaticPolynomials = "1.3.4"
ThreadSafeDicts = "0.0.2"
Zygote = "~0.6.10"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
